spring:
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        serviceId: ead-config-server
      username: configserver
      password: 'ead123cs'
